#+TITLE: Antworten zum Arbeitsblatt: Adjektivendungen 2

* A. Endungen. Ergänzen Sie die Endungen für die Adjektive!

1.	Ich lese gerade ein interessant[es] Buch (n).  	14.	Woher hast du dieses wunderschön[e] Bild (n)?
2.	Das ist billig[er] Wein (m). Ich kaufe nur  	15.	Das ist nicht für ein klein[es] Kind (n).
 	   teur[en] Wein.  	16.	Wir verkaufen frisc[h]e Äpfel (pl) und
3.	Ich habe diese lustig[e] Geschichte (f) nicht  	 	   warm[es] Brot (n).
 	   verstanden.  	17.	Es ist ein alt[er] Brief (m) von einig[en]
4.	Herbert ist ein gut[er] Freund (m) von mir.  	 	   deutsch[en] Freund[en] (pl).
5.	Es gibt hier leider keine gut[en] Museen (pl).  	18.	Bei schlecht[em] Wetter (n) bleiben wir zu
6.	Der alt[e] braun[e] Mantel (m) ist dort.  	 	   Hause.
7.	Er arbeitet in einer klein[en] Bäckerei (f).  	19.	Wir suchen ein klein[es] Haus (n) mit einem
8.	Dieser lang[e] Brief (m) ist von meiner  	 	   groß[en] Garten (m).
 	   französisch[en] Freundin (f).  	20.	Die ander[en] Leute (pl) sind in ein teures
9.	Die braun[en] Socken (pl) kosten fünf Euro.  	 	   Restaurant (n) gegangen.
10.	Wir nehmen den gelb[en] Pulli (m).  	21.	Ich wünsche dir einen gut[en] Tag (m)!
11.	In dieser Stadt sind schon viel[e] schön[e]  	22.	Sie sieht gern französisch[e] Filme (pl).
 	   alt[e] Häuser (pl).  	23.	Du hast doch solche höflich[en] Kinder (pl)!
12.	Darf ich mit amerikanisch[em] Geld (n) bezahlen?  	24.	Auf der Party habe ich viel[e] jung[e]
13.	Peter hat das neu[e] Auto (n) von seinen  	 	   Leute (pl) getroffen.
 	   reich[en] Eltern (pl) bekommen.  	25.	Ich habe alle italienisch[en] Filme (pl) in den
 	  	 	   letzt[en] 10 Jahren (pl) gesehen.


* B. Brief von einer geärgerten Hausfrau. Ergänzen Sie die Endungen in diesem Brief.

Mein lieb[er] Mann (m),
du sagst, ich soll mich ein bisschen entspannen. Aber ich habe genug gehabt! Weißt du eigentlich, was ich den ganz[en] Tag (m) mache? Während du noch in deinem warm[en] Bett (n) schläfst, wecke ich unsere klein[en] Kinder (pl). Dann mache ich in der kalt[en] Küche (f) das groß[e] Frühstück (n). Endlich verlässt du dein schön[es] warmes Bett (n), und du setzt dich an den gedeckt[en] Tisch (m). Du liest deine lang[e] Zeitung (f), und ich helfe den laut[en] Kindern (pl) bei ihren letzt[en] Hausaufgaben (pl). Nachdem ihr alle aus dem Haus seid, muss ich das schmutzig[e] Geschirr (dinnerware) (n) spülen und die ganz[e] Wäsche (f) waschen. Ich muss auch bei gut[em] und schlecht[em] Wetter (n) in dem groß[en] Garten (m) arbeiten und den ganz[en] Haushalt (m) in Ordnung bringen. Denn wenn mein müd[er] Mann (m) von seiner schwer[en] Arbeit (f) nach Hause kommt, möchte er ein sauber[es] ordentlich[es] Haus (n) finden. Mein lieb[er] Mann (m): Haushalt und Beruf sind die gemeinsam[e] Aufgabe (f) von beid[en] Eheleuten (pl).
Mit nicht so herzlich[en] Grüßen (pl) von deiner geärgert[en] Frau (f).
