#+TITLE: Antworten zum Arbeitsblatt: Adjektivendungen 4

* A. Schreiben Sie die richtigen Endungen in die Lücken ein.

Hier vor dem klein[en] Haus steht eine nett[e] alt[e] Dame. Sie hat einen etwas ungewöhnlich[en] Namen, weil sie nicht aus diesem Teil des groß[en] Landes kommt. Lucinda Amalia Camilla de Torres heißt die klein[e] grauhaarig[e] Frau, die aus dem sonnig[en] Land Spanien kommt. Sie wohnt aber seit vielen Jahren hier in dem kalt[en] Norden. Spanisch[e] Frauen bleiben nicht seht oft hier; sie leben lieber in warm[em] Süden. Lucinda aber war schon lange nicht mehr in ihrer schön[en] Heimat (homeland), weil sie zu alt für die lang[e] Reise ist.


* B. Ergänzen Sie die Endungen und auch die Artikel (der/einen/etc.) für diese Geschichte.

Es hat einmal ein[e] gut[e] Mutter mit ihr[em] klein[en] Kindchen in ein[em] ruhig[en] Dorf gewohnt. Sie hat zu ihr[er] klein[en] Tochter gesagt: “Geh mal zu dein[er] alt[en] Großmutter, und bring ihr dies[e] gut[e] Flasche Wein und dies[en] frisch[en] Kuchen. Aber du mußt in d[em] dunkl[en] Wald aufpassen, weil dort d[er] böse Wolf wohnt.” D[as] klein[e] Mädchen ist mit sein[er] groß[en] Tasche in d[en] grün[en] Wald gegangen. Auf d[em] dunkl[en] Weg ist d[er] bös[e] Wolf gekommen und hat d[as] klein[e] Mädchen gefragt, wo sein[e] alt[e] Großmutter wohnt. Er hat d[em] gut[en] Kind auch d[ie] wunderbar[en] Blumen am Weg gezeigt.

Dann hat d[er] furchtbar[e] Wolf d[ie] arm[e] Großmutter gefressen und hat sich in d[as] bequem[e] Bett d[er] alt[en] Frau gelegt. D[as] müd[e] Rotkäppchen ist in d[as] klein[e] Haus gekommen und hat gefragt: “Großmutter, warum hast du solch[e] groß[en] Ohren? Warum hast du solch[e] groß[en] Augen? Und warum hast du so ein[en] groß[en] Mund?” Da hat d[er] bös[e] Wolf geantwortet: “Damit ich dich besser fressen kann!”

Nun ja, Sie kennen das Ende dies[er] bekannt[en] Geschichte. D[er] Jäger hat d[en] dick[en] Wolf getötet und d[as] klein[e] Mädchen und sein[e] alt[e] Großmutter aus d[em] Bauch d[es] tot[en] Wolfes gebracht.


* C. Ergänzen Sie die Endungen und die Artikel in den Sätzen.

1.	Hast du dies[es] toll[e] Buch gelesen?
2.	Dein alt[er] braun[er] Mantel liegt auf dem Stuhl.
3.	Er kauft d[en] neu[en] Wagen nicht.
4.	Wo ist euer neu[es] Auto?
5.	Ich kaufe ein[en] neu[en] Anzug.
6.	Ich lese neu[e] Romane gern.
7.	Er fährt mit d[em] neu[en] Zug.
8.	Das Restaurant hat kalt[es] und warm[es] Essen.
9.	Viel[e] jung[e] Menschen kommen aus klein[en] Städten.
10.	Es gibt kein[e] gut[en] Restaurants in dies[er] langweilig[en] Stadt.
11.	Ich trinke gut[en] Wein gern.
12.	Wem gehört dies[er] neu[e] Wagen?
13.	Das Buch hat einig[e] gut[e] Beispiele.
14.	Wir fahren mit ein[em] ander[en] Schiff.
15.	Ah, das ist ein schön[es] Hemd!
16.	Was machen wir mit dies[er] häßlich[en] Lampe?
17.	Welch[en] alt[en] Mann meinst du?
