#+TITLE: Antworten zum Arbeitsblatt: Adjektivendungen 3

* I. Adjektivendungen mit “EIN”-Wörtern. Schreiben Sie die richtige Endung, wo eine Endung logisch ist.

Meine klein[e] Schwester zieht sich gern schön an. Heute trägt sie einen sehr modern[en] Hut und einen braun[en] Mantel. Sie trägt meine grün[en], italienisch[en] Schuhe und einen weiß[en] Rock mit einer schön[en] Seidenbluse. Ein groß[es] Problem für sie ist, daß sie kein Geld hat, also kann sie sich keine teur[en] und schön[en] Kleider kaufen.

* II. Adjektivendungen mit “DER”-Wörtern. Schreiben Sie die richtige Endung, wo eine Endung logisch ist.

Dieser nett[e] Mann ist sehr fleißig und hat viel Geld. Die lustig[e] Frau von dem nett[en] Mann heißt Annette. Das schnell[e], teur[e] Auto, das die reich[en] Leute haben, steht vor dem groß[en] Haus auf der ruhig[en] Straße. Die klein[en] Kinder von den zwei reich[en] Leuten gehen in diese teur[e] Schule. Ihre Kleidung ist auch nicht billig[X]. Das ist typisch für diese snobistisch[en] Leute!

* III. Übungen nach Kasus. Füllen Sie die Lücken mit den richtigen Artikeln und Endungen ein.

** Nominativ:
D[er] schnell[e] Zug fährt nach Kiel. (Das ist ein[e] schön[e] Stadt!) D[as] modern[e] Hotel liegt am Hafen. Groß[e] Schiffe kommen an und fahren ab. Ein[X] alt[er] Mann, vielleicht der Kapitän, steht auf einem Schiff und raucht eine Zigarette.

** Akkusativ:
Der Kapitän sieht in d[as] tief[e], klar[e] Wasser und raucht sein[e] amerikanisch[]e Zigarette. Er hört laut[e], fröhlich[e] Kinder am Land und schaut sie an. Die Kinder laufen durch ein[en] kleine[n] Park, denn sie haben ein[en] jung[en], braun[en] Hund entdeckt!

** Dativ:
Ich gehe aus mein[em] modern[en] Hotel zum groß[en] Schiff. Ich spreche mit d[em] alt[en] Kapitän. Er sagt aber nichts. Im Park spielt der Hund mit d[en] klein[en], laut[en] Kinder[]n. Fische schwimmen in klar[em], blau[em] Wasser. Wir stehen unter d[er] heiß[en] Sonne.

IV. Sätze mit “EIN”-Wörtern. Schreiben Sie den Satz um, und benutzen Sie dabei die Wörter in Klammern.

BEISPIEL:  Wo ist der alte Computer? (mein)   -	Wo ist mein alter Computer?
1.	Wo ist der neue Wecker? (mein)	[Wo ist mein neuer Wecker?]
2.	Wo ist der rote Regenschirm? (dein)	[Wo ist dein roter Regenschirm?]
3.	Roberto hat ein Zimmer. (neu)	[Roberto hat ein neues Zimmer.]
4.	Das Zimmer hat einen Balkon. (privat)	[Das Zimmer hat einen privaten Balkon.]
5.	Hast du das schöne Geschenk? (dein)	[Hast du dein schönes Geschenk?]
6.	Wo liegt das schwarze Hemd? (ihr)	[Wo liegt ihr schwarzes Hemd?]
7.	Der alte Hund heißt Rolf. (sein)	[Sein alter Hund heißt Rolf.]


V. Sätze zusammenstellen. Stellen Sie die zwei Sätze zusammen; benutzen Sie dabei die angegebenen Adjektive.

BEISPIEL:  Wir haben in einem Restaurant gegessen. Es war gut.  -  Wir haben in einem guten Restaurant gegessen.

1.	Die Mädchen arbeiten in einem Büro. Sie sind intelligent, und es ist groß.
 [	Die intelligenten Mädchen arbeiten in einem großen Büro.]
2.	Wir haben in einer Diskothek getanzt. Sie war toll.
 	[Wir haben in einer tollen Diskothek getanzt.]
3.	Möchten Sie in unserer Stadt wohnen? Sie ist klein.
 	[Möchten Sie in unserer kleinen Stadt wohnen?]
4.	Heinz wohnt bei seinen Eltern. Sie sind alt.
 	[Heinz wohnt bei seinen alten Eltern.]
5.	Inge ist mit ihren Freunden zusammen. Sie sind jung.
 	[Inge ist mit ihren jungen Freunden zusammen.]
6.	Das ist ein Gedicht von meinem Professor. Er ist alt.
 	[Das ist ein Gedicht von meinem alten Professor.]


VI. Übersetzen. Übersetzen Sie die folgenden Sätze ins Deutsche!

1.	The happy students speak good German with their (pick an adjective) teacher.
 	[Die glücklichen Studenten sprechen gutes Deutsch mit ihrer netten Lehrerin.]
2.	Old friends are the best (=best) friends.
 	[Alte Freunde sind die besten Freunde.]
3.	Our old dog ate the new shoes of our friendly father.
 	[Unser alter Hund hat die neuen Schuhe von unserem freundlichen Vater gegessen.]
4.	She went to a fabulous restaurant and saw a great (=toll) movie.
 	[Sie ist in ein fantastisches Restaurant gegangen und hat einen tollen Film gesehen.]
5.	This new chapter has hard grammar and bad sentences.
 	[Dieses neue Kapitel hat schwere Grammatik und schlechte Sätze.]
