#+TITLE: Antworten zum Arbeitsblatt: Relativpronomen 2

* A. Lückentext: Relativpronomen. Fill in the blanks with the appropriate relative pronoun (and a preposition where needed!). Remember to watch for case and gender!

1.	Ist das _Haus_ schön? Du möchtest eines Tages _das Haus_ kaufen.
 	  -  Ist das Haus, [das] du eines Tages kaufen möchtest, schön?

2.	Sozialgeschichte ist ein interessanter _Bereich_ (=subject area). Ich interessiere mich _für diesen Bereich_.
 	  -  Sozialgeschichte ist ein interessanter Bereich, [für den] ich mich interessiere.

3.	Die _Familie_ ist nach Griechenland geflogen. Ihr habt _bei der Familie_ gewohnt.
 	  -  Die Familie, [bei der] ihr gewohnt habt, ist nach Griechenland geflogen.

4.	Die Firma sucht _Mitarbeiter_ (pl). _Sie_ sind jung und freundlich.
 	  -  Die Firma sucht Mitarbeiter, [die] jung und freundlich sind.

5.	Der Hund schläft auf dem _Teppich_. Ich habe _den Teppich_ letzten Monat gekauft.
 	  -  Der Hund schläft auf dem Teppich, [den] ich letzten Monat gekauft habe.

6.	Der _Affe_ heißt Fritz. Du sollst _ihm_ für die Banane danken.
 	  -  Der Affe, [dem] du für die Banane danken sollst, heißt Fritz.

7.	Ich bin ein _Mensch_. _Mir_ ist der Frieden (=peace) wichtig.
 	  -  Ich bin ein Mensch, [dem] der Frieden wichtig ist.


* B. Ganze Sätze. Make one complete sentence (main clause + relative clause) out of the two provided. You’ll need to just repeat at least the beginning of the first sentence, and turn the second sentence into a relative clause.

1.	Ich kaufe das _Haus_. _Das Haus_ steht an der Ecke.
 [Ich kaufe das Haus, das an der Ecke steht].
ODER: Das Haus, das ich kaufe, steht an der Ecke.

2.	Ist das dort die _Studentin_? Du hast _mit ihr_ gesprochen.
 	[Ist das dort die Studentin, mit der du gesprochen hast]?

3.	Hamburg hat viele _Museen_. Wir wollen _die Museen_ besuchen.
 	[Hamburg hat viele Museen, die wir besuchen wollen].
ODER: Die Museen, die Hamburg hat, wollen wir besuchen.

4.	Die _Studenten_ studieren Jura. Wir haben _ihnen_ ein Zimmer gemietet (=rented).
 	[Die Studenten, denen wir ein Zimmer gemietet haben, studieren Jura].
ODER: Wir haben den Studenten, die Jura studieren, ein Zimmer gemietet.

5.	Kennst du den _Mann_? Er hat den gelben Anzug getragen.
 	[Kennst du den Mann, der den gelben Anzug getragen hat]?

6.	Das ist ein _Problem_. Es gibt keine Lösung _für das Problem_.
 	[Das ist ein Problem, für das es keine Lösung gibt].

7.	Hans setzt sich auf den _Stuhl_. Er hat _den Stuhl_ gekauft.
 	[Hans setzt sich auf den Stuhl, den er gekauft hat.]
ODER: Er hat den Stuhl, auf den er sich setzt, gekauft.


* C. Ein bisschen mehr. This section may be harder, because there’s nothing for you to refer to. You’ll need to fill in the blanks with the appropriate relative pronoun, based on the gender of the noun it represents and the case it takes in the relative clause.

1.	Barbara hat die Bücher (pl), mit [denen] wir gelernt haben.
2.	Das ist der Film (m), [den] Frau Schmidt sehen will.
3.	Ist das der Park (m), durch [den] wir gelaufen sind?
4.	Das ist das Kind (n), [dem] ich gestern geholfen habe.
5.	Die Leute (pl), von [denen] du ein Sofa gekauft hast, wohnen jetzt in Berlin.
6.	Das Buch gehört der Studentin (f), [die] neben mir gesessen hat.
7.	Dort steht das Auto (n), in [dem] ich meine Tasche gelassen habe.


* D. Frei erfinden. Complete the sentences in your own words by writing a relative clause.

1.	-- Welcher Film ist das?
 	-- Das ist der Film, [den ich gestern gesehen habe]. (Oder: ... der den Oscar gewonnen hat.).

2.	-- Wem hast du den Brief gegeben?
 	-- Es war ein Mann, [der einen Hut getragen hat]. (Oder: ... den ich auf der Strasse gesehen habe.).

3.	-- Möchtest du in ein anderes Restaurant gehen?
 	-- Ja, gehen wir in ein Restaurant, [das billiger ist]. (Oder: ... in dem wir sprechen können.).

4.	-- Warum heißt das Baby Helga?
 	-- Helga war der Name von einer guten Freundin, [die ich als Kind gekannt habe]. (Oder: ... von der wir viel Geld bekommen haben.).

5.	-- Warum bist du so spät ins Bett gegangen?
 	-- Ich hatte Hausaufgaben, [die ich machen musste]. (Oder: ... auf die ich mich konzentriert habe.).


* E. Und übersetzen. Translate the sentences into German. Remember that sometimes the English sentences are structured differently than German (e.g. “that” may be left out in English, but it’s needed in German, or the preposition may be at the end in English, but at the beginning in German).

1.	Where is the coat that I bought today?
 [Wo ist der Mantel, den ich heute gekauft habe?]

2.	There’s the man I’m waiting for.
 [Dort ist der Mann, auf den ich warte.]

3.	Where is the woman who can repair my car?
 	[Wo ist die Frau, die mein Auto reparieren kann?]

4.	I bought a car that wasn’t very expensive.
 	[Ich habe ein Auto gekauft, das nicht sehr teuer war.]

5.	She has a friend she can stay with.
 [Sie hat einen Freund, bei/mit dem sie bleiben kann.]

6.	Here are the people we need to (=must) help.
 	[Hier sind die Leute, denen wir helfen müssen].

7.	This is the only (=einzige) name that I know.
 	[Das ist der einzige Name, den ich kenne].
